CREATE DATABASE MyCompany
GO

USE MyCompany
GO

-- CREATE
CREATE TABLE dbo.Employees (
	EmployeeId INT NOT NULL IDENTITY(1,1),
	EmployeeName NVARCHAR(64) NOT NULL,
	RoleId TINYINT NOT NULL,
	DepartmentId TINYINT NOT NULL,
	ProjectId SMALLINT NOT NULL,
	StartDate DATE NULL,
	TerminationDate DATE NULL,
	SysStartTime DATETIME NOT NULL CONSTRAINT DF_Employees_SysStartTime DEFAULT GETDATE(),	-- name constraint yourself, otherwise the system will create a default one
	CONSTRAINT PK_EmployeeId PRIMARY KEY CLUSTERED (EmployeeId)
);

CREATE TABLE dbo.Roles (
	RoleId TINYINT NOT NULL IDENTITY(1,1),
	RoleName NVARCHAR(32) NOT NULL,
	Description NVARCHAR(500) NULL,
	SysStartTime DATETIME NOT NULL CONSTRAINT DF_Roles_SysStartTime DEFAULT GETDATE(),
	CONSTRAINT PK_Roles PRIMARY KEY CLUSTERED (RoleId)
)

CREATE TABLE dbo.Departments (
	DepartmentId TINYINT NOT NULL IDENTITY(1,1),
	DepartmentName NVARCHAR(32) NOT NULL,
	SysStarTime DATETIME NOT NULL CONSTRAINT DF_Departments_SysStartTime  DEFAULT GETDATE(),
	CONSTRAINT PK_Departments PRIMARY KEY CLUSTERED (DepartmentId)
)

CREATE TABLE dbo.Projects (
	ProjectId SMALLINT NOT NULL IDENTITY(1,1),
	ProjectName NVARCHAR(64) NOT NULL,
	BudgetAmount DECIMAL NOT NULL,
	Description NVARCHAR(500) NULL,
	StartDate DATE NULL,
	EndDate DATE NULL,
	SysStartTime DATETIME NOT NULL CONSTRAINT DF_Projects_SysStartTime  DEFAULT GETDATE(),
	CONSTRAINT PK_Projects PRIMARY KEY CLUSTERED (ProjectId)
)

CREATE TABLE dbo.QueueMessages (
	MessageId INT NOT NULL IDENTITY(1,1),
	MessageBody NVARCHAR(256) NULL,
	SysStartTime DATETIME NOT NULL CONSTRAINT DF_QueueMessages_SysStartTime  DEFAULT GETDATE()
)

-- ALTER
ALTER TABLE dbo.Employees
ADD CONSTRAINT FK_Employees_Roles
FOREIGN KEY (RoleId) REFERENCES dbo.Roles(RoleId);

ALTER TABLE dbo.Employees
ADD CONSTRAINT FK_Employees_Departments
FOREIGN KEY (DepartmentId) REFERENCES dbo.Departments(DepartmentId);

ALTER TABLE dbo.Employees
ADD CONSTRAINT FK_Employees_Projects
FOREIGN KEY (ProjectId) REFERENCES dbo.Projects(ProjectId);

-- POPULATE (generated by ai)
SET NOCOUNT ON;
GO

DELETE FROM dbo.Employees;
DELETE FROM dbo.Projects;
DELETE FROM dbo.Departments;
DELETE FROM dbo.Roles;

/*========================================================
  Insert Roles
========================================================*/
INSERT INTO dbo.Roles (RoleName, Description)
VALUES
('Chief Financial Officer', 'Executive responsible for financial strategy, reporting, and oversight.'),
('Finance Director', 'Leads major finance functions, planning, and departmental execution.'),
('Portfolio Manager', 'Oversees investment portfolios and allocation decisions.'),
('Investment Analyst', 'Performs manager research, market analysis, and investment recommendations.'),
('Risk Manager', 'Monitors enterprise, portfolio, and operational risk exposures.'),
('Compliance Officer', 'Ensures adherence to regulatory and internal compliance standards.'),
('Operations Analyst', 'Supports finance and investment operations, controls, and reporting.'),
('Accountant', 'Handles accounting records, reconciliations, and financial reporting support.'),
('Treasury Analyst', 'Manages liquidity, cash forecasting, and treasury operations.'),
('Data Analyst', 'Builds reporting, analytics, and business intelligence for finance teams');
GO

/*========================================================
  Insert Departments
  ManagerId will be updated after employees are inserted
========================================================*/
INSERT INTO dbo.Departments (DepartmentName)
VALUES
('Corporate Finance'),
('Investment Research'),
('Risk and Compliance'),
('Operations'),
('Treasury');
GO

/*========================================================
  Insert Projects
  ManagerId will be updated after employees are inserted
========================================================*/
INSERT INTO dbo.Projects
(
    ProjectName,
    BudgetAmount,
    Description,
    StartDate,
    EndDate
)
VALUES
('Liquidity Forecasting Modernization', 250000.00, 'Upgrade liquidity forecasting models and reporting workflows.', '2025-01-15', '2025-10-31'),
('Portfolio Risk Dashboard', 400000.00, 'Develop an enterprise dashboard for portfolio and factor risk monitoring.', '2025-02-01', '2025-12-15'),
('Regulatory Reporting Automation', 300000.00, 'Automate recurring regulatory and compliance reporting processes.', '2025-03-01', '2025-11-30'),
('Expense Optimization Initiative', 150000.00, 'Identify and implement enterprise finance cost savings opportunities.', '2025-01-20', '2025-08-31'),
('Private Markets Reporting Enhancement', 350000.00, 'Improve transparency and reporting across private investment vehicles.', '2025-04-01', '2025-12-31'),
('Treasury Controls Transformation', 200000.00, 'Strengthen treasury controls and payment authorization workflows.', '2025-02-10', '2025-09-30'),
('Client Profitability Analytics', 275000.00, 'Build profitability analytics for institutional and advisory relationships.', '2025-03-15', '2025-11-15'),
('ESG Risk Integration', 180000.00, 'Integrate ESG-related risk indicators into investment review processes.', '2025-05-01', '2025-12-01'),
('Data Warehouse Finance Mart', 500000.00, 'Create a finance-focused data mart for reporting and analytics.', '2025-01-05', '2025-12-20'),
('Budget Planning Platform Upgrade', 325000.00, 'Enhance planning and forecasting capabilities for annual budgeting.', '2025-02-15', '2025-10-15');
GO

/*========================================================
  Insert 100 Employees
========================================================*/
INSERT INTO dbo.Employees
(
    EmployeeName,
    RoleId,
    DepartmentId,
    ProjectId,
    StartDate,
    TerminationDate
)
VALUES
('Olivia Bennett', 2, 1, 10, '2018-01-15', NULL),
('Ethan Carter', 3, 2, 2, '2019-03-11', NULL),
('Sophia Mitchell', 5, 3, 2, '2020-06-08', NULL),
('Liam Parker', 7, 4, 6, '2021-02-22', NULL),
('Ava Richardson', 9, 5, 1, '2017-09-18', NULL),
('Noah Brooks', 4, 2, 5, '2022-01-10', NULL),
('Emma Hayes', 8, 1, 4, '2021-07-12', NULL),
('James Foster', 6, 3, 3, '2019-11-04', NULL),
('Isabella Reed', 10, 4, 9, '2020-04-27', NULL),
('Benjamin Ward', 3, 2, 8, '2018-08-13', NULL),

('Mia Cooper', 4, 2, 2, '2021-01-18', NULL),
('Lucas Peterson', 7, 4, 9, '2020-10-05', NULL),
('Charlotte Gray', 8, 1, 10, '2019-05-14', NULL),
('Henry Simmons', 5, 3, 8, '2022-03-21', NULL),
('Amelia Price', 9, 5, 6, '2018-12-03', NULL),
('Alexander Long', 4, 2, 5, '2023-01-09', NULL),
('Harper Kelly', 10, 4, 7, '2021-06-01', NULL),
('Michael Sanders', 8, 1, 4, '2017-04-17', NULL),
('Evelyn Ross', 6, 3, 3, '2020-02-25', NULL),
('Daniel Cook', 3, 2, 2, '2019-09-09', NULL),

('Abigail Morgan', 4, 2, 5, '2022-05-16', NULL),
('Matthew Bell', 7, 4, 6, '2021-03-08', NULL),
('Ella Bailey', 8, 1, 10, '2020-09-28', NULL),
('Joseph Rivera', 5, 3, 2, '2018-06-11', NULL),
('Scarlett Bennett', 9, 5, 1, '2021-08-19', NULL),
('David Coleman', 4, 2, 8, '2023-02-13', NULL),
('Grace Jenkins', 10, 4, 9, '2019-10-07', NULL),
('Samuel Perry', 8, 1, 4, '2018-03-26', NULL),
('Chloe Powell', 6, 3, 3, '2020-12-14', NULL),
('Andrew Hughes', 3, 2, 7, '2017-11-20', NULL),

('Victoria Flores', 4, 2, 5, '2022-07-25', NULL),
('Christopher Butler', 7, 4, 9, '2019-01-30', NULL),
('Lily Simmons', 8, 1, 10, '2021-04-12', NULL),
('Joshua Foster', 5, 3, 8, '2020-08-24', NULL),
('Hannah Bryant', 9, 5, 6, '2018-05-02', NULL),
('Ryan Alexander', 4, 2, 2, '2023-03-06', NULL),
('Zoey Russell', 10, 4, 7, '2022-10-17', NULL),
('Nathan Griffin', 8, 1, 4, '2019-06-10', NULL),
('Penelope Diaz', 6, 3, 3, '2021-09-13', NULL),
('Aaron Hayes', 3, 2, 5, '2018-02-05', NULL),

('Layla Myers', 4, 2, 8, '2020-11-16', NULL),
('Thomas Ford', 7, 4, 6, '2021-12-01', NULL),
('Nora Hamilton', 8, 1, 10, '2017-10-23', NULL),
('Charles Graham', 5, 3, 2, '2019-08-15', NULL),
('Riley Sullivan', 9, 5, 1, '2022-04-04', NULL),
('Jack Wallace', 4, 2, 7, '2023-05-08', NULL),
('Aria Woods', 10, 4, 9, '2020-01-06', NULL),
('Jonathan Cole', 8, 1, 4, '2018-07-09', NULL),
('Aubrey West', 6, 3, 3, '2021-11-22', NULL),
('Levi Jordan', 3, 2, 5, '2019-02-18', NULL),

('Stella Owens', 4, 2, 8, '2022-06-27', NULL),
('Isaac Reynolds', 7, 4, 9, '2020-03-03', NULL),
('Hazel Fisher', 8, 1, 10, '2021-05-31', NULL),
('Julian Ellis', 5, 3, 2, '2018-09-12', NULL),
('Ellie Harrison', 9, 5, 6, '2019-12-16', NULL),
('Dylan Gibson', 4, 2, 5, '2023-06-19', NULL),
('Violet McCoy', 10, 4, 7, '2022-08-29', NULL),
('Gabriel Cruz', 8, 1, 4, '2017-06-05', NULL),
('Lucy Marshall', 6, 3, 3, '2020-07-20', NULL),
('Connor Ortiz', 3, 2, 8, '2021-10-11', NULL),

('Aurora Gomez', 4, 2, 2, '2022-09-05', NULL),
('Jeremiah Murray', 7, 4, 6, '2020-05-18', NULL),
('Savannah Freeman', 8, 1, 10, '2018-04-09', NULL),
('Adrian Wells', 5, 3, 8, '2021-01-25', NULL),
('Bella Webb', 9, 5, 1, '2019-07-01', NULL),
('Robert Simpson', 4, 2, 5, '2023-07-10', NULL),
('Claire Stevens', 10, 4, 9, '2022-02-14', NULL),
('Brandon Tucker', 8, 1, 4, '2017-12-11', NULL),
('Skylar Porter', 6, 3, 3, '2020-10-26', NULL),
('Jordan Hunter', 3, 2, 7, '2021-08-02', NULL),

('Paisley Hicks', 4, 2, 5, '2022-11-07', NULL),
('Evan Crawford', 7, 4, 9, '2019-04-15', NULL),
('Anna Henry', 8, 1, 10, '2018-11-19', NULL),
('Colton Boyd', 5, 3, 2, '2020-06-29', NULL),
('Caroline Mason', 9, 5, 6, '2021-02-08', NULL),
('Jaxon Morales', 4, 2, 8, '2023-08-21', NULL),
('Genesis Kennedy', 10, 4, 7, '2022-01-03', NULL),
('Nicholas Warren', 8, 1, 4, '2019-03-25', NULL),
('Kennedy Dixon', 6, 3, 3, '2018-10-30', NULL),
('Easton Ramos', 3, 2, 5, '2020-01-13', NULL),

('Sadie Reyes', 4, 2, 8, '2021-07-26', NULL),
('Jason Burns', 7, 4, 6, '2022-03-14', NULL),
('Allison Gordon', 8, 1, 10, '2017-05-22', NULL),
('Jose Herrera', 5, 3, 8, '2019-09-17', NULL),
('Autumn Vargas', 9, 5, 1, '2020-12-07', NULL),
('Cooper Wade', 4, 2, 2, '2023-09-11', NULL),
('Sarah Ruiz', 10, 4, 9, '2022-05-09', NULL),
('Jeremiah Newman', 8, 1, 4, '2018-01-29', NULL),
('Naomi Gardner', 6, 3, 3, '2021-03-15', NULL),
('Miles Stephens', 3, 2, 7, '2019-12-02', NULL),

('Elena Payne', 4, 2, 5, '2022-07-18', NULL),
('Christian Pierce', 7, 4, 9, '2020-02-10', NULL),
('Alice Berry', 8, 1, 10, '2018-08-06', NULL),
('Tyler Matthews', 5, 3, 2, '2021-06-21', NULL),
('Madelyn Arnold', 9, 5, 6, '2019-11-27', NULL),
('Brooks Wagner', 4, 2, 8, '2023-10-02', NULL),
('Piper Willis', 10, 4, 7, '2022-09-19', NULL),
('Roman Ray', 8, 1, 4, '2017-09-04', NULL),
('Ruby Watkins', 6, 3, 3, '2020-04-13', NULL),
('Greyson Olson', 3, 2, 5, '2021-01-11', NULL);
GO

-- SQL Authentication
USE MyCompany
GO

CREATE LOGIN mycompanyuser WITH PASSWORD = 'HelloWorld2026!',
DEFAULT_DATABASE = MyCompany;
GO

CREATE USER mycompanyuser FOR LOGIN mycompanyuser;
GO

ALTER ROLE db_owner ADD MEMBER mycompanyuser;
GO





